services:
  pragmatics_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pragmatics_api_dev
    environment:
      - CLASSIFIER_MODEL=distilbert_memory
    volumes:
      - ./static/distilbert_memory:/app/distilbert_memory:ro
    ports:
      - "8001:8001"
    networks:
      - webtools_network

networks:
  webtools_network:
    external: true
